### ISSUE TITLE
Problem found in network stack or setting. It can't reach outside adresses but recieve ssh connecton.

### ISSUE THREAD

**Issue by asergunov** [jethome-iot/armbian-build#1]
### What happened?

I've was trying to configure the new JetHub H1. 
* connected the Ethernet cable 
* found out ip address by mac
* connected over ssh
* changed the root password
* configuration utility was not able to find Internet so I had to put all the timezone setting manually

### How to reproduce?

* take fresh JetHub H1 with Armbian 23.11.2.jh.23.5
* connect the Ethernet cable 
* find out IP address by mac on router
* connect over ssh
* setup the root password
* setup timezone
* setup new user

try curl something - host unreachable

try ping the router - host unreachable

### Branch

main (main development branch)

### On which host OS are you observing this problem?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adeepn** [comment]
This is not a framework bug. Tech support only in Telegram https://t.me/jethomeru in working hours.
